# @package _global_

use_wandb: True

wandb:
  wandb_project: FALCON
  wandb_mode: 'online' # 'online' or 'offline' or 'disabled'
  wandb_group: null
  wandb_id: null
  wandb_entity: RAI-BD
  wandb_dir: ${experiment_dir}/.wandb
